### ISSUE TITLE
rendering/clouds.h has not been added

### ISSUE THREAD

**Issue by piroshikin** [Xenonic/VanguardEngine#57]
Hello. Your repositories are very educational for me. Thanks,
I contacted you because I did a git pull and now the build doesn't pass.

**Comment by Xenonic** [comment]
I haven't uploaded the clouds render pass files yet since it's heavily WIP right now. I removed references to it so latest master now builds. Also, if you want to run this yourself you'll need to add the model files, which I don't put in the repo. I've attached the helmet file, so unzipping that in the Assets folder will be enough to run as of 1edafec20d57e58702dce2ffab627a15c26593e5.

[Models.zip](https://github.com/Xenonic/VanguardEngine/files/8886894/Models.zip)

**Comment by piroshikin** [comment]
I understand the situation. Thanks. That's a great implementation of volume rendering. 
Also, thanks for the link to the model, I was using boombox instead, but it helps. 
I'll keep supporting you.
